### ISSUE TITLE
Ooops something went wrong, 

### ISSUE THREAD

**Issue by baynaa7** [Deeplite/neutrino-examples#7]
Hello, Im trying to run python src/hello_neutrino_classifier.py. However, I got the following message:

> 2021-12-20 11:57:44 - INFO: Starting job with ID: 2F2D7DC3
> 2021-12-20 11:57:44 - INFO: Args: 
> 2021-12-20 11:57:44 - ERROR: Ooops something went wrong, job id 2F2D7DC3
> 2021-12-20 11:57:44 - ERROR: 
> 2021-12-20 11:57:44 - INFO: Job with ID 2F2D7DC3 finished
> 2021-12-20 11:57:44 - INFO: Total execution time: 0:00:00 (d, hh:mm:ss)
> 2021-12-20 11:57:44 - INFO: Log has been exported to: /home/kpst/.neutrino/logs/2F2D7DC3-2021-12-20.elog

content of elog file is as follows:

> Z0FBQUFBQmh2X0VnSEtOVVJ2NUFPeG5VMUdWVDFLWTYxbHRyNnhxX1JTSXE2eXJuS1RJelh2c3FvTGlkVFZrVl9iTFVRTVN6MF9Ud1diSFgyaG40M2ZEVm03VVdpdTZGZ3RvOEVFeGNsZDdwNlpQcENQUTA2Q0JRU3JYYTlsMjFvM2lLdk8zdTdSZVBDN1FZMkhEN1NEaDE4M0wxazVDY2Z5NE9nX29HY0d2QnM2cWpHZXJwcVhTZXdVZU1qOVE1WUZ2MmxUU3NDcVQw
> Z0FBQUFBQmh2X0VnTURvRERTaERyZG02WEJxeTc1c1FQOG1lMF84alYtRnRObzZSNWgxT0ZHWVR3ZTRhTW85OGNHb1J0SnZaNUdTcWlUYThORW9CY25tbk9BWGYzTFgxT2twQWJraUdfNUh5VkNuWGlKbmF1YTRhTi1YZDU3QmVkcmZGWWY3TWEyMElPcGdIYzVLR1BEWWlXSVJPcElsc1p6ZUhTeWlOU1dGeUNUaC1nb1JLQWEtemV4cVB4TWFLNTBCRG43eUJQM0oz
> Z0FBQUFBQmh2X0VvVW5HcWpWRjZoZVJGUW0xbWJnRHUzVVhOUkQ4amY3UU1CekdrTnhFU0dTRk5LcWRfN0dIdEV4STRDVXNNdFYtTll3Zk50Vkp6TzA4UW8xdHBvcXVmV3B5dU9BTUlHcy1fOGIxVzhCUXZLY284N1lPeFJzNjFUNm9KWFlYaXU0cUlYWWswaFhIaXB0Rmw5YUFXMkpFeFM2bUFudGVzaW42dzFoaVVGVzV2Qy1wWXF1alFBT1M0ZWpxdFJDNnB0VzRW
> Z0FBQUFBQmh2X0VvSDFySDQydEQ5aG1oSV9qVGZGcWJJMHpsRUw3RXVmSWJidGF2RnNtVHdMZnRzUnFfU0lnV3d3Qjd1cXVNRFpLcTR5TVVrN28xdm1rMzNZZWh6Wkw0QXAyV2tRMkdrY1ZrcWlLYmF6aEREODB3TEktWDZObF9YOVVNWXIyRjdXRXRCOS1qekdIMGhlSFB4ZkZRdDhJQWYzTzc1TkdOajFBM1FOSGtCYnFsODUwPQ==
> Z0FBQUFBQmh2X0VvWHUwcE1WS1RoTEV0blBwcm9zS01zYzlBX29reGlfUDhQcl9ZdkZlQXYxem1GTHdYVlpCeFBXODVpdWY3OF9odTJLWmxTamUzS0RzOGlkU2VpaVJuMDNTVHpSY0ZNbE9Nb0lHZHNseHNZeERWU2lqMXBWU0RGZXg4Mm85SzJySnV6VFJUci1OVkFEX2UwV2xiMElrZ08ycWYwRlI3dDA5dFFsM1Q3S0hhbnBrTHJqckNsZmZ1WEcwVk4zWWFEZ0N4ME5nbURTeERDa2JyNmM0QkdNVFFWaTY4RF8zdzZZNUV4TUhsOUxMTENaNmctTk5aQW9wbUNia3k1TDMzM3EyZE8xTjlocXRNTVhZQXYzTUhQbnN6WVBKSE9KTGZPUEtEdDZ1N2dXV0pzX3Q2YVZyaEN3QS11Zl96WWduUkZqeXVzcnNNVHBXMThkcXV1MDhOOTRjRm1jQ2dvNVJoYUk2WU50MFV0Q3YwdF81OTVzSUtYSXJyTmdBSFB4RXFaWnA0UlNsaHhkazJXRXlRVW93UXhsYW5WQ1hTdjJkT3dTREZOLXBERGxWWnVsdz0=
> Z0FBQUFBQmh2X0VvdmJCMnNjdUJVa01jZHdFNlE0YzRwZURmQ0gtSUVwc09kejMtbEZ0cGpaU3AxamEwaVZwSlNSajVpazkxVEtUYzk0bnJadkZvX1dZbFMyWmpIZ2RhRnlkd0hYYWxWeGc1dTFfa0lHRjZLS2VDcTlIVUQzRVoxRUFFc2M1aU5vLThjVzJoWUlFdDFDT0RZQ3QzejBsVzBzeVJkaUNOM29GekMzRmkwemtmMjByNmgwMEFFcEs5MUJ1MlRWYzhPR2NjZjg4MHdFa1g2ZThXV2JRS1NES3BkQT09
> Z0FBQUFBQmh2X0VvVi1fdmdlMi0zT1Ixb2JPODJXcTh1Z3EtSUtBQ1RIVDVCRFFHWFJ2VUx4VElRV0Z6TTFkdVhHQlFOOUlzM2dQS3pzUVdzTUNMeDhZdUxWQ3oyanBSdGo3TllLbHpBNjBQVFJFamF5dFllZDJ1TWRWbC1GZUxNN3hKTHNuUEZ2OGJqeTJfanFYQnFHeTV1M05OQlNpSzhRPT0=
> Z0FBQUFBQmh2X0VvbHZ0RWtHZzBEcEpKcDZNMDU4UEx5TE9naUJFNnlGR1lSRGhGbFp0WmQ4NmhlQURaOW54Y2tUb0pDNlNocW91SEdVS3VyTXVHVERsbEh2cjA2NFFZRVZaWU9CMXFsRUhjX0UzOWlpYlpGdnFnMDlyOVJBUktxMm9tLWU3UDRnZTgtQjcza25adzlFbXVoOGF5dlo5eWxFNlQ3VmxsdmcyWFlRMTU0ZzlicnAySGs1TWtBa3FWcEdwRFZHcFBxRzJabWVxbmxGWkZBRGJLVVFfX0NQMVpoZmc3OWJLaURhb2NvaEtLYjdqSGJxLVNKQjkza05rWmtCV1dRVlJfQlROMEtSWkZWT3ZCM2lCRUozQjFKYURPYmJTSDhZam02dXNsLTVIMFk4ZjN3bFRHVThUbGxBNHJwa1dGcnRsM2wtT3BHekNRbmlyN3M0aTdLT19qMDM5OXVqRFRVVFl2Q3BjVzgwSVJTajd2MThUZjVFTWFRTzNXNm15SVdFNlIycE5LYV9WdUNOTVZkN3p5OEdkMFZVUS1pUHg5SFNjdHE4bHZlVVI2M0p5aGVMZ0JhMDVIOHlqb25HTmlYcUNueXVaY2xxNFRYN1hVblpSdjVsU2hBSURIY1pwcVhlUjBDVlVhMlBuN3JrY2dxeVJDdGh0TDhBTDJFNUltbmUwcDhjTjgweTZRVTNkbEotY19qNThzYndvZFA4TW9XTWtwSzQ0QmwwYzJqTm5hSWl0bkVlWnBlemw4SWxJdWpOYzZId2JKUWVnd3dnLUo4UW9idTVRSDdqLWhTblFNbEtfUjE4Umh3TlExdV9CRzRLb1RCOXVfSjh2VnZjOXYydjdhenkyVThDV1o3QjFlS213WDVYOFhvcVRwQ0Y0VkgyUGtyLWozMERGNXlmZXBpZndaN0pUX1NRRUJBOVU4NjhEQm5NRTBzVEZNV2hKcHVMUGxkUU9NendObEU0YjVhdUZkd28yVnNPVUk1NWl0clljYzQ2U1FkcU1XNEVmNnlyWEtrMjlwMDdOV2tUMXpnazlBZEIwZE9WYUNyTGlIN2w5SjJ2MDM4V3dkVC1PaXBFLW43U25DTlBGYV9tM2pBUVl4ZlFkeVJ1ZFFsWkF6aVVQWmk1bzdfMTdkUjZkbDVBOE1BWjE0ZFBtYjAwVlVSVVpVbXBVSFQ3NUYwWlZhLUVxQTRLXzEyZTcwM2ZKeDRVbzdyVUZTNGhBbk0xS1Rmb3ZhVWxtZ2xjYVJWRDVXWUctSHRYcFQtRWQ4UFFoaGtybFJydHhjYmJ1eVJITDNfaHBiZ2VmeEhzM192YUVKOElNV3FtMGR0ZW5aNE8zdk11eWxzM1NleUYwTGFRLTJZc2tTMGVWSWtCU1JaTFdDbDdtSktjb0RvbEY2S2pyUldaR1N0QnFWdmlJb2dHSm0xZEVEV2dMQm9RSUd5Q09xbTdYV3BYOWdWZkItM0g3bDJLd1hNR1Z6RU5SZy0ycVRDb1NpZEpoRWYyaHBiZ1YxcmZNZHNrejhxaEJ5T2RRd0VwWW1kN1hEN015bWM0eHhvQl9obmVHUERvZUlxeVdxY3JJaHlRZ1hTTW5jVnBucE5oNldqVG5VcnlYVHFrWVdyVjRCazJlbTFPeXVLdGZ1aElRekhFNkluNFMxNTJUbEs1YWphZGhQaVg4a1BNNllmYmZobi1WczhpX1lySUtXOEhkOTEwLVg=
> Z0FBQUFBQmh2X0VvQUlDdTV1VS1RUTJrRDhoMFhib1hXaXZvNm52dHZsc1JpWUtkSzZxUGR1VHdZMEpfd0VSVmkzNWp2NlZ1cDdBNDlqdDFDWlhFSHBfWWFmWkdhN21oQzB6bTV2aGJyeWVuNjRjbG1BT00tVlNRRnNUUExlN0N1a0pvaldBUEhhbk1uRnBtT0phMXR6ZTFqbGRyMHdKMkE4b1ZNUGZvWXFaUWJDaDQxbjhsaE1hb3RLZ3J6cHVTeGZNTy1mODM0Zmli
> Z0FBQUFBQmh2X0VvRm83VFVUdm5WSzNKaUgyeDhnank0Q3V6QVp6SmdsbXBCRVBzdnJSRTlvdzFfaWU2X3VfSWJQeDRJRnYtM2VScnhiMjRvckkwRG9OY3dqODEzOGY4T0RrOEFCSmQ1NmUzR3lOSURxTDcxY3VSVUVEY0p5SFpfb2xhaXJ4Q0l2YkVGX1VMaXEyU0FOZzktbllZZ0syXzRLMmhFUjJtVkJzUGNSbVRjZjM1TkZpT25YWTRqekFJRmpKdGcyU0tONjF3N0szN1dxMF9acUUxbldmMU9waDdkZz09
> Z0FBQUFBQmh2X0VvQnVoOVR1Y2tQUkdQUkRmODBtUWY0OFZGTXhpT3hYeFQtRXJSdnFSVFVZZ1RUbXR0WG5SeE50OGoxci1kRm1mLXlRVTFtN2EtQk9DQ0hNdE5rMERfbWVXNDZZeHlLUDFuYXpWOEVsY1M3aVl1VlhBVzFhcl9vZ2gzZXlpSmZZR2NYYWloR24zNjRJbnMzOXYyQWh6cFVtbmo5QTdRTDJiLVhUSmRrS1h3ZHEzTnZQMHpFbVNmZklBdGxoRGVQVmlvMVVzeDNDRTQyXzVYZl9yUWJ0Rm1KdThZTXJibkhWU1VuOFlWWF81c3pWX2tQb3A3WTdMaGc3V095Wmszc3lzcA==

even I use cpu:
python src/hello_neutrino_classifier.py --device CPU, still get the same error.
what is the problem?

**Comment by yasseridris** [comment]
Looks like you have a depedency issue in your env

`pkg_resources.ContextualVersionConflict: (numpy 1.19.5 (/home/kpst/.local/lib/python3.8/site-packages), Requirement.parse('numpy==1.18.5'), {'neutrino-engine'})
" `

I suggest you either install the correct numpy version, or better yet make sure you reinstall neutrino in a new virtual env.

**Comment by baynaa7** [comment]
Thanks, it worked.

**Comment by BhandarkarPawan** [comment]
> Looks like you have a dependency issue in your env
> 
> `pkg_resources.ContextualVersionConflict: (numpy 1.19.5 (/home/kpst/.local/lib/python3.8/site-packages), Requirement.parse('numpy==1.18.5'), {'neutrino-engine'}) " `
> 
> I suggest you either install the correct numpy version, or better yet make sure you reinstall neutrino in a new virtual env.

How did you get this information?? @baynaa7 had not mentioned it in their original comment.

**Comment by yasseridris** [comment]
> > Looks like you have a dependency issue in your env
> > `pkg_resources.ContextualVersionConflict: (numpy 1.19.5 (/home/kpst/.local/lib/python3.8/site-packages), Requirement.parse('numpy==1.18.5'), {'neutrino-engine'}) " `
> > I suggest you either install the correct numpy version, or better yet make sure you reinstall neutrino in a new virtual env.
> 
> @yasseridris How did you get this information?? @baynaa7 had not mentioned it in their original comment.
> 
> I have a similar error as above and I made an issue about it [here](https://github.com/Deeplite/neutrino/issues/16)

@BhandarkarPawan Same issue.
